### ISSUE TITLE
User Verwaltung

### ISSUE THREAD

**Issue by moosberg** [moosberg/Jobaktuell#10]
# User Verwaltung

>#### PRÄAMBEL: ist eigenes Modul

## Inhalt

    - Link zu Arbeitsblatt
    - TODOs
    - Scope
    - Algorithmus und Grafik
    - Alle issues Grundstruktur und workflow

---

### Link zu Arbeitsblatt

[user_verwaltung](https://github.com/moosberg/Jobaktuell/blob/main/Konzept/Datenbank/user_verwaltung.md)

---

### TODOs

- [x] set user funktion
- [x] hashlib verschlüsseln bei set
- [x] get user funktion
- [x] hashlib ruckbau bei get
- [x] username und pwd als variablen im db_manip
Anmerkung: eigenes krypto statt hashlib, user und passwort werden im finalen Dialog/main gespeichert werden
- [x] passwort Einstieg bei kunden.py eintrag löschen
   - [x] und dann wieder rausnehmen bis finale Dialogseite fertig ist - dann ist es einmal dort der Einstieg
- [x] _locked_by in kunden.py eintrag_löschen integrieren
    - [x] dazu braucht es eine generische inputter.py funktion update_eintrag
       - [x] mit solo wenn nur 1 Wert upgedatet wird
       - [x] und mit tuple wenn mehrere Werte upgedatet werden
    - [x] die generische Funktion braucht params
       - [x] welche tabelle
       - [x] welcher Wert / welche Werteliste
       - [x] welches Feld / welche Feldnamen

Anmerkung: ich werde dazu ein eigenes Issue anlegen und auch die Problematik update Eingabeliste für inputter.py reinnehmen  

---

### Scope

- Im modul ``db_manip.py``

**Was ist die Problemstellung?**

Momentan werden ``Passwort und Username bei create, insert, update, delete = grundsätzlich bei connection.db als Klartext gesendet``.

*********************************************************************************************
Ein weiteres Problem ist die ``Persistenz. Auch wenn momentan nur 1 User ist.`` Ich schaue da schon voraus. Bei read und create ist es kein Problem, bei update und delete schon.

**Was ist der Lösungsansatz?**

In Zukunft soll der:die User:in einmal sein:ihr Passwort über funktion eingeben, ab dann soll es ``als variable mit hashwert gespeichert``sein.

Bei der Datenbankverbindung holt sich das jeweilige Modul den Hashwert zurück - Klartext scheint nie auf.

*********************************************************************************************************

Wegen Persistenz: Bei den delete und update funktionen wird ein feld:value abgefragt, das neu in jeder Tabelle eingetragen wird. ``locked_by``. Wenn der Wert defaultmäßig None ist, wird er durch den Benutzernamen ersetzt. 

Wenn die Update transaktion abgeschlossen ist (vor connection.commit()) wird der ``locked_by``wert wieder auf None gestellt. Bei Delete ist es ohnehin hinfällig.

Wenn andere:r user:in einen gesperrten Datensatz zeitgleich löschen oder updaten, erhält er:sie die Info: ``Datensatz locked by: <username>``.

---

#### Set user:

- Eingabe param user_name und user_pwd / beides string
- try:
   - hashlib verschlüsselt und speichert die beiden Werte als variable in db_manip.py
   - Print: Credentials erfolgreich angelegt - das steht jetzt in user und pwd:
   - Returnwert tuple(user, password)
- except:
   - Print: Es gab ein Problem, Credentials nicht angelegt - das steht jetzt in user und pwd:
   - Returnwert tuple(user, password)

```mermaid
graph TD
A[User gibt ein]
A1[user_name]
A2[password]
B[hashlib verschlüsselt beide]
B1[variable user_name]
B2[variable password]
A--->A1
A--->A2
A1--->B
A2--->B
B--->B1
B--->B2
```

#### Get user

- jeweilige table (kunden, ansprechpartner...) holt sich variablen user_name und password
- aus db_manip.py
- entschlüsselt diese mit hashlib
- und gibt das Ergebnis der funktion als returnwert gleich in db.connect mit

```mermaid
graph TD
A[db manip modul]
A1[hashwert user_name]
A2[hashwert password]
A--->A1
A--->A2
B[table zB kunden]
C[Funktionsbestandteil psycopg.connect\nerhält hashwerte für user und pwd\nentschlüsselt und setzt als variable ein]
B--in CRUD und allen DB Verbindungen-->C
A1--->C
A2--->C
D[DB Verbindung geglückt weiter mit CRUD etc]
D1[DB Verbindung gescheitert connection\ntry except Rückmeldung lt. jeweiliger funktion]
C--->D
C--->D1
```

#### Persistenz Concurrency

- wenn user ``delete`` oder ``update`` funktionen macht
- wird der datensatz so lange gelockt, bis die Änderung commited ist
   - sollte bereits ein lock von jemand anderem bestehen, wird die Verbindung mit Rückmeldung beendet
   - man erfährt auch welcher user gelocked hat
- nach erfolgreichem update wird das ``locked_by`` wieder auf ``None`` gestellt
- und dann ``commit``
   - das Zurücksetzen von ``locked_by`` ist bei ``delete`` natürlich nicht nötig

```mermaid
graph TD
A[DB Zugriff für delete oder update]
B[feld locked by wird auf user namen gesetzt]
A--->B
C[Update wird durchgeführt]
C1[feld locked wieder auf None zurückgesetzt]
B--->C
C--->C1
D[delete wird durchgeführt]
B--->D
```
---

### alle Issues Workflow Grundstruktur

``diesen Punkt incl. Zitat und Grafik bitte immer lassen - als Erinnerung...``

> #### Wichtig: Erste Beschreibung des Issues, TODO Liste und im Github Issue
> 
> #### aber weitere Entwicklung über VS Code und push Github. Verlinkung vom Github Issue zum Arbeitsblatt. 
> 
> #### D.h. in den Kommentaren nur Statusmeldungen wenn TODO Punkte erledigt wurden bzw. neue TODO Punkte dazukamen

```mermaid
graph TD
A[/neue Idee/]
subgraph github repository
B[(Ideensammelbecken)]
B1[Konzept Ordner im Repository]
B2[Github Projektmanagement]
end
subgraph issue
C[/neuer Issue evtl als neuer Branch wenn Code Thema\]
D[erste Beschreibung in Markdown]
E[To Do Liste]
E1[Status und Statusänderungen]
end
subgraph VS Code
F[VS Code]
F1[Ordner unter Konzept]
G[Arbeitsblatt in Markdown im VS Code nach github gepusht]
G1[known Issues]
G2[Lösungsansätze Pseudocode Codebeispiele]
H[Code]
end
A--->B
B--->B1
B--->C
C--->D
C--->E
C--evtl Übernahme wenn es eines gibt-->B2
E--über Kommentar im issue-->E1
B--->F
F--->F1
F1--->G
F1--->H
G--->G1
G--->G2
F1--über git push-->B1
```

---

**Comment by moosberg** [comment]
### Update 2023-01-21

da ohnehin rechtzeitig vor neuen Mitarbeitern die auf die DB zugreifen die locked_by Problematik angegangen wird, werden hier jetzt einmal alle Tasks geschlossen

So schaut das Testverfahren aus:

```Python
import user_verwaltung
import getpass
#user='h43u454' password='xtKtDA4saNdYdTTeo6f'

if __name__ == "__main__":
    key_pass = False
    user_name = ""
    pass_word = ""
    while not key_pass:
        user_name = getpass.getpass("Bitte User Name eingeben:  ")
        pass_word = getpass.getpass("Bitte Passwort eingeben:  ")
        if user_verwaltung.user_check("/home/robert/ToGit/Jobaktuell/Applikation/105.json", "devop", user_name, pass_word):
            key_pass = True
        else:
            print("Bitte die richtigen credentials eingeben")
        
    print("key_pass gecheckt")
    print(user_name)
    print(pass_word)
```

**Comment by moosberg** [comment]
geschlossen am 2023-01-21
